Update README

diff --git a/README b/README
--- a/README
+++ b/README
@@ -11,5 +11,8 @@ java -classpath ".;target\spring-batch-example-0.0.1-SNAPSHOT.jar;src\main\resou
 #To run job on Linux:
 java -classpath ".:target/spring-batch-example-0.0.1-SNAPSHOT.jar:src/main/resources:./target/dependency/*" org.springframework.batch.core.launch.support.CommandLineJobRunner spring/import-products-job-context.xml importProducts inputResource=classpath:/input/products.zip targetDirectory=./target/importproductsbatch/ targetFile=products.txt
 
-#Print exit code:
+#Print exit code in Windows:
 echo $LastExitCode
+
+#Print exit code in Linux:
+echo $?
